---
title: "Family Unit Simulation"
author: "Bryan Kim"
date: "6/26/2020"
output: pdf_document
---


```{r}
##### Installing Packages ####
library(dplyr)

### Functions used ###
# Finds the missing integer in vector of integers
missing_int=function(vec) {
    n = length(vec) 
    total = (n + 1)*(n + 2)/2
    sum_of_vec = sum(vec) 
    return(total - sum_of_vec)
}
## Draws a random number from a uniform distribution (0,delta)
rand_time=function(){
  return(runif(1,0,delta))
}
## Draws a random number from a uniform distribution (0,delta)
test_correct=function(){
  return(runif(1,0,1))
}
## Randomly infects one person from the n family members
rand_inf=function(){
  return(sample.int(n,1))
}

## S->E Transition time random draw
susc_exp=function(curr_time){
  return(curr_time+rexp(1,(1/h*R0f*gamma_I)))
}
## E->I Transition time random draw
exp_infect=function(curr_time){
  return(curr_time+rexp(1,(1/gamma_E)))
}
## I->R Transition time random draw
infect_recov=function(curr_time){
  return(curr_time+rexp(1,(1/gamma_I)))
}

##### Setting Parameters, Functions, and initial conditions #####
R0f=5;gamma_E=1/R0f;n=7;gamma_I=1/n;delta=1;p=0.7;h=0.5

# Random time drawn and random infected person drawn
t=rand_time()
infect=rand_inf()

# Initialize State and Time Vectors
State=rep("S",n)
Time=rep(0,n)

################################################################################


#### Next Action Time ####
action_time=function() {
  temp_action_Time=Time
  assign('temp_action_Time',temp_action_Time,envir = .GlobalEnv)
  
  # print(Time) 
  
  # if no one is infected (E and below), Susceptible members have infinite (very large) values. If there is an E, only update   their time value
 if (!("I" %in% State)) {
   
  # print("I is not in State")
   
   ## If only S and E in State
   if ((("S" %in% unique(State)) & ("E" %in% unique(State)) & (length(unique(State))==2))) {
    # Assigning big values for S individuals
    s=which(State=="S")
    temp_action_Time[s]=10000000
    e=which(State=="E")
    for (e in e) {
        temp_action_Time[e]=exp_infect(temp_action_Time[e])
    }
    
  #  print(State)
  #  print(temp_action_Time)
    
    assign('temp_action_Time',temp_action_Time,envir = .GlobalEnv)
    return(min(temp_action_Time))
   }
  ## If only R and S in State vector
   else if ((("R" %in% unique(State)) & ("S" %in% unique(State)) & (length(unique(State))==2))) {
     
   #print("Only R and S in State")
     
    s=which(State=="S")
    for (s in s) {
        temp_action_Time[s]=susc_exp(temp_action_Time[s])
      }    
    r=which(State=="R")
    temp_action_Time[r]=1000000
    
  #  print(State)
  #  print(temp_action_Time)
    
    assign('temp_action_Time',temp_action_Time,envir = .GlobalEnv)
    return(min(temp_action_Time))
   }
   ## If only R and E in State vector
   else if ((("R" %in% unique(State)) & ("E" %in% unique(State)) & (length(unique(State))==2))) {
     
   #print("Only R and E in State")
     
    e=which(State=="E")
    for (e in e) {
        temp_action_Time[e]=exp_infect(temp_action_Time[e])
      }    
    r=which(State=="R")
    temp_action_Time[r]=1000000
    
    #print(State)
    #print(temp_action_Time)
    
    assign('temp_action_Time',temp_action_Time,envir = .GlobalEnv)
    return(min(temp_action_Time))
   }
  else {
    # Everything but I
    
    #print("Stuff")
    
      # Assigning big values for S individuals
      s=which(State=="S")
      for (s in s) {
          temp_action_Time[s]=susc_exp(temp_action_Time[s])
        }      
      e=which(State=="E")
      for (e in e) {
          temp_action_Time[e]=exp_infect(temp_action_Time[e])
      }
      r=which(State=="R")
      temp_action_Time[r]=1000000
      
   #   print(State)
   #   print(temp_action_Time)
      
      assign('temp_action_Time',temp_action_Time,envir = .GlobalEnv)
      return(min(temp_action_Time))

}
 }
  else { #(("S" %in% State) | ("E" %in% State) | ("I" %in% State)) 
    
  #  print("I IS in State")
    
    # Updating Infect_Duration
    i=which(State=="I")
    Infect_Duration[i]=Infect_Duration[i]+temp_action_Time[i]
    assign('Infect_Duration',Infect_Duration,envir = .GlobalEnv)
    
  #  print("printing Infect_Duration")
    
   # print(Infect_Duration)
    
    # Modifying S state individuals
      s=which(State=="S")
      for (s in s) {
        temp_action_Time[s]=susc_exp(temp_action_Time[s])
      }
      assign('temp_action_Time',temp_action_Time,envir = .GlobalEnv)
    # Modifying E state individuals
      e=which(State=="E")
      for (e in e) {
        temp_action_Time[e]=exp_infect(temp_action_Time[e])
      }
      assign('temp_action_Time',temp_action_Time,envir = .GlobalEnv)
    # Modifying I state individuals
      i=which(State=="I")
      for (i in i) {
        temp_action_Time[i]=infect_recov(temp_action_Time[i])
      }
      # Should we make the R people's action time infinite too?
      r=which(State=="R")
      for (r in r) {
        temp_action_Time[r]=1000000
      }
      assign('temp_action_Time',temp_action_Time,envir = .GlobalEnv)
      
      #print(State)
    #print(temp_action_Time)
      
  return(min(temp_action_Time))
  }
  
}

################################################################################

#### Next Test Time ####
test_time=function() {
  
  #print(delta)
  
  temp_test_Time=delta
  assign('temp_test_Time',temp_test_Time,envir = .GlobalEnv)
  return(temp_test_Time)
}

################################################################################

##### Algorithm #####
algo=function(t,infect,R0f,gamma_E,gamma_I,n,delta,p,h) {
  # creating original delta variable for updating our delta values.
  delta_orig=delta
  assign('delta_orig',delta_orig,envir = .GlobalEnv)
  delta=delta
  assign('delta',delta,envir = .GlobalEnv)
  # First iteration process
  State[infect]="E"
  Time=rep(t,n)
  assign('State',State,envir = .GlobalEnv)
  assign('Time',Time,envir = .GlobalEnv)
  
 # print(State)
 # print(Time)
 # print("CHECK")
  
  # index to see how many iterations it takes
  i=0
  # index to see how many people have been tested
  c=0
  # index to update delta
  d=1
  assign('d',d,envir = .GlobalEnv)
  
  ### First checks if R is the only element in State vector ###
  while ((!(("R" %in% unique(State)) & (length(unique(State))==1)))) {
      i=i+1
      
     # print("CHECKWHILE")
      
      #### if we do not stop the algo:
      ### run action_time & test_time
      ## if action_time < test_time: then update the value of the smallest temp_Time index to simulate disease progression. 
      if (isTRUE(action_time()<test_time())) {
        
       # print("ACTION<TEST")
        
        # Updating Time vector
        Time[1:length(Time)]=min(temp_action_Time)
        assign('Time',Time,envir = .GlobalEnv)
        
       # print("ACTION")
        
        # Updating one individual in the State vector depending on smallest time.
        
        #  print(State)
        
        if (State[which(temp_action_Time==min(temp_action_Time))]=="S") {
          State[which(temp_action_Time==min(temp_action_Time))]="E"
          assign('State',State,envir = .GlobalEnv)
        #  print("S to E")
        }
        else if (State[which(temp_action_Time==min(temp_action_Time))]=="E") {
          State[which(temp_action_Time==min(temp_action_Time))]="I"
          assign('State',State,envir = .GlobalEnv)
        #  print("E to I")
        }
        else { #(State[which(temp_action_Time==min(temp_action_Time))]=="I" 
          State[which(temp_action_Time==min(temp_action_Time))]="R"
          assign('State',State,envir = .GlobalEnv)
        #  print("I to R")
        }
      }
      ### else test_time < action_time ###
      else  {
        
        # If the test work then proceed
        if (test_correct()<p) {
        
        if ((!(("R" %in% unique(State)) & ("S" %in% unique(State))&(length(unique(State))==2)))){
        c=c+1
      #  print("TEST<ACTION")
        
        # Here we test an infected person so commence end process calculations
        if ((State[delta/delta_orig]=="I")) {
  #        print("Tested an infected person")   #
            # go to end process calculations
            break 
          
        }
        # If we do not test an infected person
        else  {
          
       #   print("Did not Test and Infected person")
          
          # Updating Time vector
          Time[1:length(Time)]=temp_test_Time
          assign('Time',Time,envir = .GlobalEnv)
          # Updating State vector
        }
        # cycle through which person to test
        if ((delta/delta_orig)==n) {
          delta=delta_orig
          assign('delta',delta,envir = .GlobalEnv)
          d=1
          assign('d',d,envir = .GlobalEnv)
          
  #        print("HI")
  #        print(delta)
        }
        else {
          delta=delta_orig*(d+1)
          assign('delta',delta,envir = .GlobalEnv)
          d=d+1
          assign('d',d,envir = .GlobalEnv)
          
  #        print("Hello")
  #        print(delta)
        }
        }
        else {
#        print(paste("There is only S and R after",i,"iterations - end process"))   #
        break
        }
        
        }
        else {
          # test did NOT work
#         print("Test did NOT work")   #
        }
    #  print(State)
      }
    }
    assign('State',State,envir = .GlobalEnv)
    assign('Time',Time,envir = .GlobalEnv)
    assign('delta',delta,envir = .GlobalEnv)
    assign('delta',delta,envir = .GlobalEnv)
  
    #### End Process Calculations ####
    
    # What is delta?
#    print(paste("Delta =",delta))   #
    
  #print("DO END PROCESS CALCULATIONS")
  #print(Time)  
#  print(State) #
    
#  print(paste("Number of iterations =",i))  #
  #return(i)
#  print(paste(c,"people were tested"))  #
      
  ## Number of members that are Exposed or higher ##
  exp=sum(("E"==State)|("I"==State)|("R"==State))
  assign('exp',exp,envir = .GlobalEnv)
#  print(paste("Number of individuals Exposed or higher =",sum(("E"==State)|("I"==State)|("R"==State))))  #
  ## Duration each person has been infected
  assign('Infect_Duration',Infect_Duration,envir = .GlobalEnv)
#  print("Duration of time each individual is infected:")  #
#  print(Infect_Duration)  #

#  print(" ") #
}


```


```{r}
######### Run Simulation Once #########
R0f=5;gamma_E=1/R0f;n=20;gamma_I=1/n;delta=1;p=0.7;h=0.5
t=rand_time()
infect=rand_inf()
# Initialize State and Time Vectors
State=rep("S",n)
Time=rep(0,n)
Infect_Duration=rep(0,n)
# Run algorithm
algo(t,infect,R0f,gamma_E,gamma_I,n,delta,p,h)
```


```{r}
######### Run Simulation n times #########

## Manipulating size of Group ##

Fraction=c()

num_sim=60

exp_vec=c()
infect_dur_vec=c()
for (i in 1:num_sim) {
#   print(paste("Simulation",i))    #
R0f=5;gamma_E=1/R0f;n=7;gamma_I=1/n;delta=0.1;p=0.7;h=0.5
t=rand_time()
infect=rand_inf()
# Initialize State and Time Vectors
State=rep("S",n)
Time=rep(0,n)
Infect_Duration=rep(0,n)
# Run algorithm
algo(t,infect,R0f,gamma_E,gamma_I,n,delta,p,h)
# Assign to vectors/lists for graphs
exp_vec=append(exp_vec,exp)
infect_dur_vec=append(infect_dur_vec,Infect_Duration)

if (i==num_sim) {
  # Getting the mean fraction of people E or above
frac<<-(mean(exp_vec)/n)
# Getting the mean time people are infectious in each group for 
mean_infect_total_sim=colMeans(matrix(infect_dur_vec,n))
mean_infect<-mean(mean_infect_total_sim)
 assign('frac',frac,envir = .GlobalEnv)
 assign('mean_infect',mean_infect,envir = .GlobalEnv)

}

}
Fraction=append(Fraction,frac)

#print(frac)
#print(mean_infect)



```

```{r}

## Changing n (2 to 20), holding delta constant at 1
Frac_dt=data.table(Fraction)
# Creating data table
for (i in 1:19) {
  Frac_dt$x[i]=i+1
}

ggplot(Frac_dt,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (delta=1)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.50, 1.0, 0.1), limits=c(0.50, 1.0)) 

```


```{r}

## Changing n (2 to 20), holding delta constant at 0.5
Frac_0.5_dt=data.table(Fraction)
# Creating data table
for (i in 1:19) {
  Frac_0.5_dt$x[i]=i+1
}

ggplot(Frac_0.5_dt,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (delta=0.5)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.50, 1.0, 0.1), limits=c(0.50, 1.0)) 


```


```{r}
Fraction=Fraction[-length(Fraction)]
## Changing n (2 to 20), holding delta constant at 2
Frac_dt_del=data.table(Fraction)
# Creating data table
for (i in 1:length(Frac_dt_del$Fraction)) {
  Frac_dt_del$x[i]=i+1
}

ggplot(Frac_dt_del,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (delta=2)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 34, 3), limits=c(2, 34)) +
  scale_y_continuous(breaks=seq(0.40, 1.0, 0.1), limits=c(0.40, 1.0)) 


```

```{r}
Fraction=Fraction[-length(Fraction)]
## Changing n (2 to 20), holding delta constant at 2
Frac_dt2=data.table(Fraction)
# Creating data table
for (i in 1:19) {
  Frac_dt2$x[i]=i+1
}

ggplot(Frac_dt2,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (delta=2)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.70, 1.0, 0.1), limits=c(0.70, 1.0)) 


```

```{r}
Fraction=Fraction[-length(Fraction)]
## Changing n (5 to 20), holding delta constant at 5
Frac_dt3=data.table(Fraction)
# Creating data table
for (i in 5:19) {
  Frac_dt3$x[i-4]=i
}

ggplot(Frac_dt3,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (delta=5)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(5, 19, 3), limits=c(5, 19)) +
  scale_y_continuous(breaks=seq(0.7, 1.0, 0.1), limits=c(0.70, 1.0)) 


```



```{r}

## Changing delta (starting at 1), holding n constant at 7
Frac_delta_dt=data.table(Fraction)
for (i in 1:length(Frac_delta_dt$Fraction)) {
  Frac_delta_dt$x[i]=i
}
ggplot(Frac_delta_dt,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (n=7)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("Delta") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(1, 7, 1), limits=c(1, 7)) +
  scale_y_continuous(breaks=seq(0.6, 1.0, 0.1), limits=c(0.6, 1.0)) 
```


```{r}

## Changing delta (starting at 1), holding n constant at 15
Frac_delta2_dt=data.table(Fraction)
for (i in 1:length(Frac_delta2_dt$Fraction)) {
  Frac_delta2_dt$x[i]=i
}
ggplot(Frac_delta2_dt,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (n=15)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("Delta") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(1, 15, 1), limits=c(1, 15)) +
  scale_y_continuous(breaks=seq(0.6, 1.0, 0.1), limits=c(0.6, 1.0)) 
```


```{r}

## Changing delta (0.1,0.4,0.7,1.0,1.3,1.6,1.9), holding n constant at 7
Frac_delta3_dt=data.table(Fraction)
g=1
for (i in seq(0.1,10,0.3)) {
  Frac_delta3_dt$x[g]=i
  g=g+1
}
ggplot(Frac_delta3_dt,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (n=7)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("Delta") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(0.1, 10.1, 0.4), limits=c(0.1, 10.1)) +
  scale_y_continuous(breaks=seq(0.3, 1.0, 0.1), limits=c(0.3, 1.0)) 
```


```{r}
## Infected Times!!

## Changing n (2 to 20), holding delta constant at 0.5
Infect_0.5_dt=data.table(Infected)
# Creating data table
for (i in 1:19) {
  Infect_0.5_dt$x[i]=i+1
}

ggplot(Infect_0.5_dt,aes(x=x,y=Infected)) +
  geom_point() +
  ggtitle("Mean Time each Family is Infected for (delta=0.5)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Total Time")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.8, 2, 0.2), limits=c(0.8, 2)) 

ggsave("Fract_n1_20_del0.5.pdf",height=9,width=11,dpi=72)
```

```{r}
## Infected Times!!

## Changing n (2 to 20), holding delta constant at 1
Infect_dt=data.table(Infected)
# Creating data table
for (i in 1:19) {
  Infect_dt$x[i]=i+1
}

ggplot(Infect_dt,aes(x=x,y=Infected)) +
  geom_point() +
  ggtitle("Mean Time each Family is infected for (delta=1)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Total Time")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(1.5, 2.7, 0.2), limits=c(1.5, 2.7)) 

ggsave("Fract_n1_20_del1.pdf",height=9,width=11,dpi=72)

```


```{r}
## Infected Times!!

## Changing n (2 to 20), holding delta constant at 2
Infect2_dt=data.table(Infected)
# Creating data table
for (i in 1:19) {
  Infect2_dt$x[i]=i+1
}

ggplot(Infect2_dt,aes(x=x,y=Infected)) +
  geom_point() +
  ggtitle("Mean Time each Family is Infected for (delta=2)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Total Time")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(1.9, 4.2, 0.5), limits=c(1.9, 4.2)) 

ggsave("Fract_n1_20_del2.pdf",height=9,width=11.5,dpi=72)

```



```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding delta constant at 0.5
Fract_dt5=data.table(Fraction)
# Creating data table
for (i in 1:19) {
  Fract_dt5$x[i]=i+1
}

ggplot(Fract_dt5,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (delta=0.5)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.4, 1.0, 0.1), limits=c(0.4, 1.0)) 

ggsave("Fract_n2_20_del3.pdf",height=9,width=11.5,dpi=72)

```



```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding delta constant at 1
Fract_dt6=data.table(Fraction)
# Creating data table
for (i in 1:19) {
  Fract_dt6$x[i]=i+1
}

ggplot(Fract_dt6,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (delta=1)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.5, 1.0, 0.1), limits=c(0.5, 1.0)) 

ggsave("Fract_n2_20_del1.pdf",height=9,width=11.5,dpi=72)

```


```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding delta constant at 2
Fract_dt4=data.table(Fraction)
# Creating data table
for (i in 1:19) {
  Fract_dt4$x[i]=i+1
}

ggplot(Fract_dt4,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (delta=2)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.6, 1.0, 0.1), limits=c(0.6, 1.0)) 

ggsave("Fract_n2_20_del4.pdf",height=9,width=11.5,dpi=72)

```

```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding delta constant at 6
Fract_dt6=data.table(Fraction)
# Creating data table
for (i in 1:19) {
  Fract_dt6$x[i]=i+1
}

ggplot(Fract_dt6,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (delta=6)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.6, 1.0, 0.1), limits=c(0.6, 1.0)) 

ggsave("Fract_n2_20_del6.pdf",height=9,width=11.5,dpi=72)

```

```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding delta constant at 1
Fract_dt5=data.table(Fraction)
# Creating data table
for (i in 1:19) {
  Fract_dt5$x[i]=i+1
}

ggplot(Fract_dt5,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (delta=1)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.4, 1.0, 0.1), limits=c(0.4, 1.0)) 

ggsave("Fract_n2_20_del3.pdf",height=9,width=11.5,dpi=72)

```

```{r}
## Infected Times!!

## Changing delta (0.1 to 2), holding n constant at 7
Infect3_dt=data.table(Infected)
# Creating data table
g=1
for (i in seq(0.1,2,0.3)) {
  Infect3_dt$x[g]=i
  g=g+1
}

ggplot(Infect3_dt,aes(x=x,y=Infected)) +
  geom_point() +
  ggtitle("Mean Time each Family is Infected for (n=7)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("delta") +
  ylab("Total Time")+
  scale_x_continuous(breaks=seq(0.1, 2, 0.3), limits=c(0.1, 2)) +
  scale_y_continuous(breaks=seq(0, 4, 0.4), limits=c(0, 4)) 
```


```{r}
## Infected Times!!

## Changing delta (0.1 to 10), holding n constant at 4
Infect4_dt=data.table(Infected)
# Creating data table
g=1
for (i in seq(0.1,10,0.3)) {
  Infect4_dt$x[g]=i
  g=g+1
}

ggplot(Infect4_dt,aes(x=x,y=Infected)) +
  geom_point() +
  ggtitle("Mean Time each Family is Infected for (n=4)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("delta") +
  ylab("Total Time")+
  scale_x_continuous(breaks=seq(0.1, 10, 0.5), limits=c(0.1, 10)) +
  scale_y_continuous(breaks=seq(0, 13, 1), limits=c(0, 13)) 
```


```{r}
## Infected Times!!

## Changing delta (0.1 to 10), holding n constant at 7
Infect5_dt=data.table(Infected)
# Creating data table
g=1
for (i in seq(0.1,10,0.3)) {
  Infect5_dt$x[g]=i
  g=g+1
}

ggplot(Infect5_dt,aes(x=x,y=Infected)) +
  geom_point() +
  ggtitle("Mean Time each Family is Infected for (n=7)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("delta") +
  ylab("Total Time")+
  scale_x_continuous(breaks=seq(0.1, 10.1, 0.5), limits=c(0.1, 10.1)) +
  scale_y_continuous(breaks=seq(0, 13, 1), limits=c(0, 13)) 

ggsave("Infect_del01_10.pdf",height=9,width=12,dpi=72)
```


```{r}
## Infected Times!!

## Changing delta (0.1 to 10), holding n constant at 15
Infect6_dt=data.table(Infected)
# Creating data table
g=1
for (i in seq(0.1,10,0.3)) {
  Infect6_dt$x[g]=i
  g=g+1
}

ggplot(Infect6_dt,aes(x=x,y=Infected)) +
  geom_point() +
  ggtitle("Mean Time each Family is Infected for (n=15)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("delta") +
  ylab("Total Time")+
  scale_x_continuous(breaks=seq(0.1, 10, 0.5), limits=c(0.1, 10)) +
  scale_y_continuous(breaks=seq(0, 11, 1), limits=c(0, 11)) 

ggsave("Infect_del01_10.pdf",height=9,width=12,dpi=72)
```



```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding n constant at 7
Fract_dt7=data.table(Fraction)
# Creating data table
g=1
for (i in seq(0.1,10,0.3)) {
  Fract_dt7$x[g]=i
  g=g+1
}

ggplot(Fract_dt7,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (n=7)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("delta") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(0.1, 10.1, 0.5), limits=c(0.1, 10.1)) +
  scale_y_continuous(breaks=seq(0.3, 1.0, 0.1), limits=c(0.3, 1.0)) 

ggsave("Fract_n2_20_del7.pdf",height=9,width=11.5,dpi=72)

Fract_dt7$"n=7"="n=7"

```















```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding n constant at 5
Fract_dt8=data.table(Fraction)
# Creating data table
g=1
for (i in 2:20) {
  Fract_dt8$x[g]=i
  g=g+1
}

ggplot(Fract_dt8,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (n=5)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("delta") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.4, 1.0, 0.1), limits=c(0.4, 1.0)) 

names(Fract_dt8)[1]="del=0.5"


```


```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding n constant at 15
Fract_dt9=data.table(Fraction)
# Creating data table
g=1
for (i in 2:20) {
  Fract_dt9$x[g]=i
  g=g+1
}

ggplot(Fract_dt9,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (n=5)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("delta") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.4, 1.0, 0.1), limits=c(0.4, 1.0)) 


names(Fract_dt9)[1]="del=1.5"


```


```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding n constant at 5
Fract_dt10=data.table(Fraction)
# Creating data table
g=1
for (i in seq(0.1,10,0.3)) {
  Fract_dt10$x[g]=i
  g=g+1
}

ggplot(Fract_dt10,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (n=5)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("delta") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.4, 1.0, 0.1), limits=c(0.4, 1.0)) 

names(Fract_dt10)[1]="n=4"


```



```{r}
## Fraction E or Higher!!

Fract_dt11=data.table(Fraction)
# Creating data table
g=1
for (i in seq(0.1,10,0.3)) {
  Fract_dt11$x[g]=i
  g=g+1
}

ggplot(Fract_dt11,aes(x=x,y=Fraction)) +
  geom_point() +
  ggtitle("Mean Fraction of People Exposed or Higher (n=5)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("delta") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.4, 1.0, 0.1), limits=c(0.4, 1.0)) 

names(Fract_dt11)[1]="n=7"

```



```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding n constant at 5
Fract_dt12=data.table(Infected)
# Creating data table
g=1
for (i in seq(0.1,10,0.3)) {
  Fract_dt12$x[g]=i
  g=g+1
}

ggplot(Fract_dt12,aes(x=x,y=Infected)) +
  geom_point() +
  ggtitle("Mean Infected Time (n=4)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("delta") +
  ylab("Infected")+
  scale_x_continuous(breaks=seq(0.1,10,0.3), limits=c(0.1, 10)) +
  scale_y_continuous(breaks=seq(0.3, 14.0, 0.1), limits=c(0.3, 14.0)) 

names(Fract_dt12)[1]="n=4"


```



```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding n constant at 5
Fract_dt13=data.table(Infected)
# Creating data table
g=1
for (i in seq(0.1,10,0.3)) {
  Fract_dt13$x[g]=i
  g=g+1
}

ggplot(Fract_dt13,aes(x=x,y=Infected)) +
  geom_point() +
  ggtitle("Mean Infected Time (n=4)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("delta") +
  ylab("Infected")+
  scale_x_continuous(breaks=seq(0.1,10,0.3), limits=c(0.1, 10)) +
  scale_y_continuous(breaks=seq(0.3, 16.0, 0.1), limits=c(0.3, 16.0)) 

names(Fract_dt13)[1]="n=7"


```

```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding delta constant at 0.5
Fract_dt14=data.table(Infected)
# Creating data table
g=1
for (i in 2:20) {
  Fract_dt14$x[g]=i
  g=g+1
}

ggplot(Fract_dt14,aes(x=x,y=Infected)) +
  geom_point() +
  ggtitle("Mean Infected Time (delta=0.5)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.4, 1.0, 0.1), limits=c(0.4, 1.0)) 

names(Fract_dt14)[1]="del=0.5"


```


```{r}
## Fraction E or Higher!!

## Changing n (2 to 20), holding delta constant at 0.5
Fract_dt15=data.table(Infected)
# Creating data table
g=1
for (i in 2:20) {
  Fract_dt15$x[g]=i
  g=g+1
}

ggplot(Fract_dt15,aes(x=x,y=Infected)) +
  geom_point() +
  ggtitle("Mean Infected Time (delta=0.5)") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  xlab("n") +
  ylab("Fraction")+
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.4, 1.0, 0.1), limits=c(0.4, 1.0)) 

names(Fract_dt15)[1]="del=1.5"


```


```{r}
test1=cbind(Fract_dt14,Fract_dt15)
test1.0=reshape2::melt(test1,id.var="x")
Figure1 = ggplot(test1.0,aes(x=x,y=value)) +
  geom_line(aes(linetype=variable, colour=variable),size=1.002) +
  scale_color_manual(values=c("dodgerblue","darkorange2","gray")) +
  xlab("delta") +
  ylab("Time")+
  ggtitle("Mean Infected Time") +
  theme_bw() +
  theme(plot.title = element_text(hjust=0.50)) +
  scale_x_continuous(breaks=seq(2, 20, 3), limits=c(2, 20)) +
  scale_y_continuous(breaks=seq(0.5, 4.0, 0.5), limits=c(0.5, 4.0)) 
  theme(legend.position="bottom") 
Figure1
ggsave("del2.pdf",height=9,width=11.5,dpi=72)


```

